###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: 
- jekyll-feed
- jekyll-menus

###############################################################################
# Page Personal Details
url: http://ydaalm.github.io/
baseurl: /
author: Hayda Almeida
title: Hayda Almeida | Personal page
description: Personal page
avatar: hayda.jpg

# Contacts
email: marcia_soares.hayda@courrier.uqam.ca

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
#username: haydaalmeida
github: ydaalm
twitter: haydaalmeida
linkedin: haydaalmeida
# Research Outputs
google_scholar: UwiTmJ0AAAAJ

 
